# -*- coding: utf-8 -*-
"""DairyAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vG-ILTtGLY4QPYoBup1mdr7tmX75tMTQ
"""

!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("dairy_dataset.csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

"""**Check if any column have unwated data value**"""

df['Location'].unique()

df['Farm Size'].unique()

df['Product ID'].unique()

df['Product Name'].unique()

df['Brand'].unique()

df['Storage Condition'].unique()

df['Customer Location'].unique()

df['Sales Channel'].unique()

"""**Preprocess Date Column**"""

df['Date'] = pd.to_datetime(df['Date'])
df['Production Date'] = pd.to_datetime(df['Production Date'])
df['Expiration Date'] = pd.to_datetime(df['Expiration Date'])

df.head()

df.info()

"""**Extract new columns**"""

df['Production Month No'] = df['Production Date'].dt.month
df['Production Year'] = df['Production Date'].dt.year
df['Expiration Month No'] = df['Expiration Date'].dt.month
df['Expiration Year'] = df['Expiration Date'].dt.year

df['Production Month'] = df['Production Date'].dt.month_name()
df['Expiration Month'] = df['Expiration Date'].dt.month_name()

df.head()

ax = sns.countplot(x= 'Product Name', data = df)
ax.bar_label(ax.containers[0])
plt.xticks(rotation = 90)
plt.show

plt.figure(figsize= (4,4))
gb = df.groupby('Product Name')['Quantity (liters/kg)'].sum()
plt.pie(gb, labels = gb.index, autopct = '%.2f')
plt.show()

from google.colab import files

df.to_csv('dairy.csv', index=False)
files.download('dairy.csv')